//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosiness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusBooking
    {
        public int StatusBookingID { get; set; }
        public string StatusBookingName { get; set; }
    }
}
